name = "Rauschen"
uuid = "c3eb8a58-8e99-4680-9810-8cdc52ad6cea"
authors = ["Leonard Kilian Eyer <leonard.eyer@fastmail.de>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
